### ISSUE TITLE
Improved feature list

### ISSUE THREAD

**Issue by Rucknium** [Rucknium/CashFusionStats#2]
This issue creates a feature roadmap for CashFusionStats. Test versions of these features will first appear at https://beta.redteam.cash and on the git repo branch `beta`. Input and feedback welcome.

## Fees

- [ ] Calculate and display some measure of the fee per user per CashFusion transaction
- [ ] Display the value of this fee in fiat terms.

## CashFusion UTXO set

- [ ] Calculation of current quantity of BCH and number of outputs in the "CashFusion UTXO set". CashFusion UTXO set here is defined as all outputs of CashFusion transactions that have not yet been spent.
  - [ ] Display of current quantity of BCH in CashFusion UTXO set as a single number
  - [ ] Line graph of CashFusion UTXO set, in terms of quantity of BCH and number of outputs
- [ ] Line graph over time of how much BCH is being spent from the CashFusion "shielded pool", in terms of number of outputs and quantity of BCH. Such a transaction is defined as spending an output from a CashFusion transaction in any transaction that is not a CashFusion transaction.
- [ ] The same as above, but the number of outputs and quantity of BCH that are _entering_ the CashFusion "shielded pool".

From the above, we will have the stock quantity (CashFusion UTXO set), and two flow quantities (inflows and outflows from the CashFusion UTXO set).

## Risky user behavior

- [ ] Identify and aggregate transactions that use inputs from both CashFusion transactions and non-CashFusion transactions.
  - [ ] Create a line graph that tracks the number of such transactions over time.
- [ ] (Maybe) Identify spends where a large number of outputs are pulled from CashFusion transactions.

**Comment by emergent-reasons** [comment]
I don't think you reasonably say anything about fee "per user" because... well if you could then fusion isn't working. What you can say is fee per fused BCH, fee per input or other aggregates that might be useful.

**Comment by emergent-reasons** [comment]
A histogram of fusion-utxo coin value would be interesting by itself as well as scratching the surface of the issues of actual anonymity.

**Comment by emergent-reasons** [comment]
It's tied up in a bunch of the others, but specific numbers on how fusion affects the size of the overal utxo set. If it generally is helping to reduce small utxos that are passed over usually by wallet coin choosers, that could make it a great force for keeping the utxo set efficient.

**Comment by emergent-reasons** [comment]
Generally speaking, I like to see numbers that have an intent and question behind them as the primary focus, although having exploratory data available is nice also.

**Comment by Rucknium** [comment]
@emergent-reasons Thank you for your input!

> I don't think you reasonably say anything about fee "per user" because... well if you could then fusion isn't working. What you can say is fee per fused BCH, fee per input or other aggregates that might be useful.

We cannot get a precise "per user" number, but I do think an decent estimate of the average is possible. If we can get an estimate of the average number of users per CashFusion transaction -- which I think is roughly possible -- then we can get an estimate. I'd like to emphasize the low cost of CashFusions for users compared to BTC CoinJoins. The other metrics that you mentioned can be added as well -- and maybe they should be added first so that I can mull over how best to estimate fee per user per transaction. I don't want to say anything that's incorrect of course, so I will be careful.

> A histogram of fusion-utxo coin value would be interesting by itself as well as scratching the surface of the issues of actual anonymity.

Good idea. I think it's feasible to add a slider as well so that one can see how the histogram evolves over time.

> It's tied up in a bunch of the others, but specific numbers on how fusion affects the size of the overal utxo set. If it generally is helping to reduce small utxos that are passed over usually by wallet coin choosers, that could make it a great force for keeping the utxo set efficient.

This is an interesting angle. I hadn't thought of that. I will have to think about how to approach this question.
